Importa biblioteca de algebra linear

In [1]:
import numpy as np

Estabelece sequência de bits para cada personagem, característica entre outros.

In [89]:
#Personagens:

D = [1, -1, 1, -1, 1]  #Drumond
C = [1, 1, 1, -1, -1]  #Chico Buarque
Po = [1, 1, -1, -1, 1] #Portinari

#Áreas:

L = [1, -1, 1, -1]  #Literatura
M = [1, 1, -1, -1]  #Música
Pi = [1, -1, -1, 1] #Pintura

#Cidades: 

I = [-1, 1, -1, 1] #Itabira
R = [1, 1, -1, 1]  #Rio de Janeiro
B = [-1, -1, 1, 1] #Brod.

Junção dos personagens:

In [158]:
Per = np.c_[D, C, Po]      #Personagens

Junção das características

In [133]:
Are = np.c_[L, M, Pi]      #Área
Cid = np.c_[I,R,B]         #Cidade

Car = np.c_[Are.T,Cid.T]   #Junção de área e cidade

Matriz resultante da unção:

In [134]:
print(Car)

[[ 1 -1  1 -1 -1  1 -1  1]
 [ 1  1 -1 -1  1  1 -1  1]
 [ 1 -1 -1  1 -1 -1  1  1]]


Criando a matriz de pesos:

In [136]:
W = np.dot(Car.T,Per.T)

In [159]:
print(W)

[[ 3  1  1 -3  1]
 [-1  1  1  1 -3]
 [-1 -3  1  1  1]
 [-1  1 -3  1  1]
 [-1  1  1  1 -3]
 [ 1 -1  3 -1 -1]
 [-1  1 -3  1  1]
 [ 3  1  1 -3  1]]


Fazendo a transformação:

In [160]:
np.sign(W)

array([[ 1,  1,  1, -1,  1],
       [-1,  1,  1,  1, -1],
       [-1, -1,  1,  1,  1],
       [-1,  1, -1,  1,  1],
       [-1,  1,  1,  1, -1],
       [ 1, -1,  1, -1, -1],
       [-1,  1, -1,  1,  1],
       [ 1,  1,  1, -1,  1]])