In [1]:
import numpy as np

In [44]:
# Alternativa:

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

# Área de espera:

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

# Sexta ou sábado:

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

# Estou com fome: 

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

# Lotacão:

nenhum = [1, -1, -1, -1] #Caso tenha nenhuma pessoa
pouco  = [1, 1, -1, -1]  #Caso tenha poucas pessoas
cheio  = [1, 1, 1, -1]   #Caso esteja lotado

# Preço:

caro =   [-1, -1, -1, 1] #Caso seja caro
medio =  [-1, -1, 1, 1]  #Caso seja razoável
barato = [-1, 1, 1, 1]   #Caso seja barato

# Chovendo:

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

# Reserva: 

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

# Tempo estimado: 

dez      = [1, -1, -1, 1]
vinte    = [1, -1, 1, -1]
trinta   = [-1, 1, -1, 1]
sessenta = [-1, 1, 1, -1]

# Esperar

sim = [1, 1, 1, 1]     #Caso seja sim
nao = [-1, -1, -1, -1] #Caso seja não

In [53]:
#Saídas

# Existe alternativa de restaurante:
alter = [sim,sim,nao,sim,sim,nao,nao,nao,nao,sim,nao,sim]
# Existe área de espera:
area  = [nao,nao,sim,nao,nao,sim,sim,nao,sim,sim,nao,sim]
# É sexta ou sábado:
sORs  = [nao,nao,nao,sim,sim,nao,nao,nao,sim,sim,nao,sim]
# Estou com fome:
strv  = [sim,sim,nao,sim,nao,sim,nao,sim,nao,sim,nao,sim]
# Lotação do espaço:
alot  = [pouco,cheio,pouco,cheio,cheio,pouco,nenhum,pouco,cheio,cheio,nenhum,cheio]
# Preço:
price = [caro,barato,barato,barato,caro,medio,barato,medio,barato,caro,barato,barato]
# Está chovendo:
rain  = [sim,nao,nao,nao,sim,sim,nao,sim,nao,sim,sim,nao]
# Foi feito reserva:
reser = [sim,nao,nao,nao,sim,sim,nao,sim,nao,sim,nao,nao]
# Tempo estimado de espera:
time  = [dez,trinta,dez,vinte,sessenta,dez,dez,dez,sessenta,vinte,dez,trinta]

#Entrada

# Esperar:
wait  = [sim,nao,sim,sim,nao,sim,nao,sim,nao,nao,nao,sim]

In [65]:
# Crio a matriz como do exercício, porém codificada:
car = np.c_[alter,area,sORs,strv,alot,price,rain,time]

In [66]:
# Confiro se a matriz está ok:
print(car)

[[ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1 -1 -1 -1 -1 -1  1
   1  1  1  1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1 -1 -1  1  1  1
  -1 -1 -1 -1 -1  1 -1  1]
 [-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1 -1 -1  1  1  1
  -1 -1 -1 -1  1 -1 -1  1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  1 -1 -1  1  1  1
  -1 -1 -1 -1  1 -1  1 -1]
 [ 1  1  1  1 -1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1 -1 -1 -1 -1  1
   1  1  1  1 -1  1  1 -1]
 [-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1  1  1  1  1  1  1 -1 -1 -1 -1  1  1
   1  1  1  1  1 -1 -1  1]
 [-1 -1 -1 -1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1 -1 -1  1  1  1
  -1 -1 -1 -1  1 -1 -1  1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1 -1 -1 -1 -1  1  1
   1  1  1  1  1 -1 -1  1]
 [-1 -1 -1 -1  1  1  1  1  1  1  1  1 -1 -1 -1 -1  1  1  1 -1 -1  1  1  1
  -1 -1 -1 -1 -1  1  1 -1]
 [ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 -1 -1 -1 -1  1
   1  1  1  1  1 

In [62]:
# Faço o produto da entrada pela matriz (transversa) das características:
W = np.dot(car.T,wait)

In [64]:
# Imprimo o resultado:
print(W)

[[ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [-2 -2 -2 -2]
 [-2 -2 -2 -2]
 [-2 -2 -2 -2]
 [-2 -2 -2 -2]
 [ 6  6  6  6]
 [ 6  6  6  6]
 [ 6  6  6  6]
 [ 6  6  6  6]
 [ 0  0  0  0]
 [ 4  4  4  4]
 [-4 -4 -4 -4]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [-2 -2 -2 -2]
 [ 2  2  2  2]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]
 [ 4  4  4  4]
 [-4 -4 -4 -4]
 [-4 -4 -4 -4]
 [ 4  4  4  4]]
